### ISSUE TITLE
Configuration schema

### ISSUE THREAD

**Issue by codinaut** [codinaut/helm-preset#1]
Objectives:
- Zero (auto) configuration.
- Explicit supersedes auto-configuration, like how Helm merges objects.

**Comment by codinaut** [comment]
1st schema iteration:
```
order:
  - cloud
  - environment

includePath: presets
categories:
  cloud:
    eks: {}
    gke: {}
  environment:
    staging: {}
    production: {}
```

**Comment by codinaut** [comment]
2nd schema iteration:
```
includePath: presets
categories:
  - cloud:
    includeEmpty: true
    presets:
      eks: {}
      gke: {}
  - environment:
    includeEmpty: true
    presets:
      staging: {}
      production: {}
```

**Comment by codinaut** [comment]
3nd schema iteration:
```yaml
includes:
  - presets
categories:
  - name: cloud
    includeEmpty: true
    presets:
      eks: {}
      gke: {}
  - name: environment
    includeEmpty: true
    presets:
      staging: {}
      production: {}
```
