### ISSUE TITLE
Configuration schema

### ISSUE THREAD

**Issue by codinaut** [codinaut/helm-preset#1]
- Zero (auto) configuration.
- Explicit supersedes auto-configuration, like Helm merge one.

**Comment by codinaut** [comment]
1st schema iteration:
```yaml
order:
  - cloud
  - environment

includePath: presets
types:
  cloud:
    eks: {}
    gke: {}
  environment:
    staging: {}
    production: {}
```

**Comment by codinaut** [comment]
2nd schema iteration:
```yaml
includePath: presets
categories:
  - cloud:
    includeEmpty: true
    presets:
      eks: {}
      gke: {}
  - environment:
    includeEmpty: true
    presets:
      staging: {}
      production: {}
```
